version: '3.8'

services:
  test:
    build:
      context: .
      target: test
    volumes:
      - ./TestResults:/app/TestResults
  
  build:
    build:
      context: .
      target: build
  
  pack:
    build:
      context: .
      target: publish
    volumes:
      - ./artifacts:/app/artifacts 