name: CI/CD

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        target: test
        load: true
        tags: aggregatekit:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run tests in Docker
      run: docker run --rm aggregatekit:test
    
    - name: Build NuGet package
      if: success() && github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        target: publish
        load: true
        tags: aggregatekit:publish
    
    - name: Extract NuGet package
      if: success() && github.event_name != 'pull_request'
      run: |
        mkdir -p ./artifacts
        docker create --name extract aggregatekit:publish
        docker cp extract:/app/artifacts/. ./artifacts/
        docker rm extract
    
    - name: Upload artifacts
      if: success() && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg
        
  publish:
    needs: build-and-test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate 